<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>cs.rug.runtime</groupId>
    <artifactId>runtime</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <packaging>pom</packaging>

    <name>Runtime</name>
    <description>Convenience aggregator for Runtime services.</description>

    <modules>
        <module>process-registry-service</module>
        <module>observation-service</module>
        <module>camunda-8-integration</module>
        <module>camunda-8-worker-service</module>
        <module>co2-calculation-service</module>
        <module>kei-evaluation-service</module>
        <module>mock-operational-service</module>
        <module>monitoring-results-service</module>
    </modules>
</project>
