<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>cs.rug.gbpmruntime</groupId>
    <artifactId>gbpmruntime</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <packaging>pom</packaging>

    <name>GBPMRuntime</name>
    <description>Convenience aggregator for GBPMRuntime services.</description>

    <modules>
        <module>gbpmruntime-process-registry</module>
        <module>gbpmruntime-observation</module>
        <module>camunda-8-integration</module>
        <module>camunda-8-worker-service</module>
        <module>co2-calculation-service</module>
        <module>kei-evaluation-service</module>
        <module>mock-operational-service</module>
        <module>monitoring-results-service</module>
    </modules>
</project>
